# Generated by Django 3.2.8 on 2021-10-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
